#ifndef WATERBEAR_SENSOR_TYPES
#define WATERBEAR_SENSOR_TYPES

#define GENERIC_ANALOG_SENSOR 0x0000
#define GENERIC_ATLAS_SENSOR 0x0001
#define NO_SENSOR 0xFFFF

#define MAX_SENSOR_TYPE 0x0001

#endif